from _collections_abc import AsyncGenerator # Importing the AsyncGenerator class from the _collections_abc module for type hinting asynchronous generator functions
import uuid # Importing the uuid module for generating unique identifiers

from sqlalchemy import Column, String, Text, DateTime, ForeignKey # Importing necessary modules and classes from SQLAlchemy for database operations
from sqlalchemy.dialects.postgresql import UUID # Importing the UUID type from the PostgreSQL dialect of SQLAlchemy
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker # Importing necessary modules and classes from SQLAlchemy for database operations
from sqlalchemy.orm import DeclarativeBase, relationship # Importing necessary modules and classes from SQLAlchemy for database operations
from datetime import datetime # Importing the datetime module for handling date and time operations
from fastapi_users.db import SQLAlchemyUserDatabase, SQLAlchemyBaseUserTableUUID # Importing the SQLAlchemyBaseUserTable class for integrating FastAPI Users with SQLAlchemy
from fastapi import Depends # Importing the Depends function from FastAPI for handling dependencies in route functions

DATABASE_URL = "postgresql+asyncpg://postgres:Marion78!@localhost:5432/fastapi_db"

class Base(DeclarativeBase):
    pass # Defining a base class for the declarative model using SQLAlchemy's DeclarativeBase

class User(SQLAlchemyBaseUserTableUUID, Base): # Defining a User model that inherits from the Base class and SQLAlchemyBaseUserTableUUID for user management
    posts = relationship("Post", back_populates="user") # Establishing a relationship between the User model and the Post model for database operations
class Post(Base):
    __tablename__ = "posts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4) # Defining the id column as a UUID primary key with a default value generated by uuid.uuid4
    user_id = Column(UUID(as_uuid=True), ForeignKey("user.id"), nullable=False) # Defining the user_id column as a UUID foreign key that references the id column in the user table and cannot be null
    caption = Column(Text) # Defining the caption column as a Text type for storing longer text data
    url = Column(String, nullable=False) # Defining the url column as a String that cannot be null
    file_type = Column(String, nullable=False) # Defining the file_type column as a String that cannot be null
    file_name = Column(String, nullable=False) # Defining the file_name column as a String that cannot be null
    created_at = Column(DateTime, default=datetime.utcnow) # Defining the created_at column as a DateTime with a default value of the current UTC time

    user = relationship("User", back_populates="posts") # Establishing a relationship between the Post model and the User model for database operations


engine = create_async_engine(DATABASE_URL) # Creating an asynchronous engine for the database connection
async_session = async_sessionmaker(engine, expire_on_commit=False) # Creating an asynchronous session maker for managing database sessions


async def create_db_and_tables(): # Defining an asynchronous function to create the database and tables
    async with engine.begin() as conn: # Establishing an asynchronous connection to the database
        await conn.run_sync(Base.metadata.create_all) # Running the create_all method to create the tables defined in the DeclarativeBase metadata

async def get_async_session() -> AsyncGenerator[AsyncSession, None]: # Defining an asynchronous generator function to yield an asynchronous session
    async with async_session() as session: # Establishing an asynchronous session using the async_session maker
        yield session # Yielding the asynchronous session for use in database operations

async def get_user_db(session: AsyncSession = Depends(get_async_session)):
    yield SQLAlchemyUserDatabase(session, User) # Defining an asynchronous generator function to yield a SQLAlchemyUserDatabase instance for integrating FastAPI Users with SQLAlchemy, using the provided session and User model